### ISSUE TITLE
Channel names are broken in #stream

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/streambot#4]
![F5938809-6D1F-4D08-A3F8-CAE43D414483](https://user-images.githubusercontent.com/5074763/83345590-f2522600-a2e2-11ea-8024-57caffd05bc5.jpeg)

**Comment by zachlatta** [comment]
This is unfortunately an issue with Slack versions that is a result of #2.

The new Slack clients properly link the channel names. The old Slack clients on iOS (I think iPad in particular) don't.

If you're able to reproduce this on desktop, let me know (I'm assuming screenshot is from iOS).

For now, am going to consider this an issue that will be fixed when the iOS clients get updated.
